MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  BACKBONE:
    NAME: "build_dilated_resnet_backbone"
  DILATED_RESNET:
    NORM: "SyncBN"
  SEM_SEG_HEAD:
    NAME: "DANetHead"
    COMMON_STRIDE: 8
    CONVS_DIM: 64
    IN_FEATURES: ["res5"]
SOLVER:
  BASE_LR: 0.01
  STEPS: (18000,)
  MAX_ITER: 24000
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1024
TEST:
  EVAL_PERIOD: 8000


