MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  BACKBONE:
    NAME: "build_dilated_resnet_backbone"
  DILATED_RESNET:
    NORM: "SyncBN"
  SEM_SEG_HEAD:
    NAME: "DANetHead"
    IN_FEATURES: ["res5"]
SOLVER:
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792, 2048, 2304)
  MAX_SIZE_TRAIN: 4608
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 4608
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: [768, 768]
TEST:
  AUG:
    ENABLED: True
    MIN_SIZES: (512, 768, 1024, 1280, 1536, 1792, 2048, 2304)
    MAX_SIZE: 4608
    FLIP: True
  EVAL_PERIOD: 5000


