_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  SEM_SEG_HEAD:
    NUM_CLASSES: 19
  DILATED_RESNET:
    DEPTH: 101
DATASETS:
  TRAIN: ("cityscapes_fine_sem_seg_train",)
  TEST: ("cityscapes_fine_sem_seg_val",)
OUTPUT_DIR: "./output/r101/cityscapes"
